version: '2'

services:
  php:
    container_name: demo_php
    build:
      context: php7-fpm
      args:
        TIMEZONE: ${TIMEZONE}
        HOST_IP: ${HOST_IP}
    volumes:
      - ${DEMO_APP_PATH}:/var/www/html/demo

  nginx:
    container_name: demo_nginx
    build:
      context: nginx
      args:
        MAX_EXECUTION_TIME: ${MAX_EXECUTION_TIME}
        SERVER_NAME: ${SERVER_NAME}
    ports:
      - "80:80"
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx
