version: '2'

services:
  php:
    container_name: demo_php
    build:
      context: php7-fpm
      args:
        TIMEZONE: ${TIMEZONE}
        HOST_IP: ${HOST_IP}
    volumes:
      - ${DEMO_APP_PATH}:/var/www/html/demo

  nginx:
    container_name: demo_nginx
    build:
      context: nginx
      args:
        MAX_EXECUTION_TIME: ${MAX_EXECUTION_TIME}
        SERVER_NAME: ${SERVER_NAME}
    ports:
      - "80:80"
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx

  db:
    container_name: demo_db
    image: mysql:8.0
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    volumes:
      - "./mysql/config:/etc/mysql/conf.d"
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_APP}
      MYSQL_USER: ${MYSQL_USER_APP}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_APP}
    ports:
      - "3306:3306"